import type { Listing, Neighborhood } from "@/types/listing";
import scrapedRaw from "@/data/scraped-listings.json";

interface RawScrapedListing {
  external_id: string;
  source: string;
  url: string | null;
  title: string;
  deal_type: "rent" | "sale";
  price: number;
  currency: string;
  area_m2: number | null;
  rooms: number | null;
  floor: number | null;
  total_floors: number | null;
  year_built: number | null;
  furnished: boolean | null;
  address: string | null;
  city: string;
  latitude: number | null;
  longitude: number | null;
  images: string[] | null;
  description: string | null;
  is_active: boolean;
}

const now = new Date().toISOString();

const ADDRESS_TO_NEIGHBORHOOD: Record<string, string> = {
  "donji grad": "Donji Grad",
  "gornji grad": "Gornji Grad",
  "gornji grad - medveščak": "Gornji Grad",
  "medveščak": "Medveščak",
  "trešnjevka - sjever": "Trešnjevka Sjever",
  "trešnjevka - jug": "Trešnjevka Jug",
  "maksimir": "Maksimir",
  "novi zagreb - istok": "Novi Zagreb Istok",
  "novi zagreb - zapad": "Novi Zagreb Zapad",
  "trnje": "Trnje",
  "črnomerec": "Črnomerec",
  "stenjevec": "Stenjevec",
  "podsljeme": "Podsljeme",
  "peščenica - žitnjak": "Peščenica",
  "peščenica": "Peščenica",
  "gornja dubrava": "Gornja Dubrava",
  "donja dubrava": "Donja Dubrava",
  "sesvete": "Sesvete",
  "podsused": "Podsused-Vrapče",
  "vrapče": "Podsused-Vrapče",
  "brezovica": "Brezovica",
};

function inferNeighborhood(address: string | null): string | null {
  if (!address) return null;
  const lower = address.toLowerCase();
  const district = lower.split(",")[0].trim();
  if (ADDRESS_TO_NEIGHBORHOOD[district]) return ADDRESS_TO_NEIGHBORHOOD[district];
  for (const [key, value] of Object.entries(ADDRESS_TO_NEIGHBORHOOD)) {
    if (lower.includes(key)) return value;
  }
  return null;
}

function toListing(raw: RawScrapedListing, idx: number): Listing {
  const area = raw.area_m2 ?? null;
  const ppm2 = area && area > 0 ? Math.round((raw.price / area) * 100) / 100 : null;
  return {
    id: `scraped-${raw.external_id}`,
    external_id: raw.external_id,
    source: raw.source,
    url: raw.url,
    title: raw.title,
    deal_type: raw.deal_type,
    price: raw.price,
    currency: raw.currency,
    area_m2: area,
    price_per_m2: ppm2,
    rooms: raw.rooms,
    floor: raw.floor ?? null,
    total_floors: raw.total_floors ?? null,
    year_built: raw.year_built ?? null,
    furnished: raw.furnished ?? null,
    neighborhood: inferNeighborhood(raw.address),
    address: raw.address,
    city: raw.city ?? "Zagreb",
    latitude: raw.latitude,
    longitude: raw.longitude,
    nearest_kindergarten_m: null,
    nearest_school_m: null,
    nearest_hospital_m: null,
    nearest_transit_m: null,
    nearest_park_m: null,
    images: raw.images,
    description: raw.description,
    scraped_at: now,
    created_at: now,
    updated_at: now,
    is_active: raw.is_active,
  };
}

export const SCRAPED_LISTINGS: Listing[] = (scrapedRaw as RawScrapedListing[]).map(toListing);

export const MOCK_NEIGHBORHOODS: Neighborhood[] = [
  { id: "donji-grad", name: "Donji Grad", city: "Zagreb", center_lat: 45.811, center_lng: 15.9785 },
  { id: "gornji-grad", name: "Gornji Grad", city: "Zagreb", center_lat: 45.815, center_lng: 15.973 },
  { id: "tresnjevka-sjever", name: "Trešnjevka Sjever", city: "Zagreb", center_lat: 45.805, center_lng: 15.955 },
  { id: "tresnjevka-jug", name: "Trešnjevka Jug", city: "Zagreb", center_lat: 45.795, center_lng: 15.95 },
  { id: "maksimir", name: "Maksimir", city: "Zagreb", center_lat: 45.823, center_lng: 16.018 },
  { id: "novi-zagreb-istok", name: "Novi Zagreb Istok", city: "Zagreb", center_lat: 45.775, center_lng: 15.995 },
  { id: "novi-zagreb-zapad", name: "Novi Zagreb Zapad", city: "Zagreb", center_lat: 45.77, center_lng: 15.95 },
  { id: "trnje", name: "Trnje", city: "Zagreb", center_lat: 45.798, center_lng: 15.988 },
  { id: "crnomerec", name: "Črnomerec", city: "Zagreb", center_lat: 45.818, center_lng: 15.94 },
  { id: "stenjevec", name: "Stenjevec", city: "Zagreb", center_lat: 45.805, center_lng: 15.91 },
  { id: "podsljeme", name: "Podsljeme", city: "Zagreb", center_lat: 45.85, center_lng: 15.95 },
  { id: "medvescak", name: "Medveščak", city: "Zagreb", center_lat: 45.827, center_lng: 15.98 },
  { id: "pescenka", name: "Peščenica", city: "Zagreb", center_lat: 45.81, center_lng: 16.01 },
  { id: "gornja-dubrava", name: "Gornja Dubrava", city: "Zagreb", center_lat: 45.835, center_lng: 16.06 },
  { id: "donja-dubrava", name: "Donja Dubrava", city: "Zagreb", center_lat: 45.82, center_lng: 16.07 },
  { id: "sesvete", name: "Sesvete", city: "Zagreb", center_lat: 45.83, center_lng: 16.11 },
  { id: "podsused-vrapce", name: "Podsused-Vrapče", city: "Zagreb", center_lat: 45.81, center_lng: 15.87 },
  { id: "brezovica", name: "Brezovica", city: "Zagreb", center_lat: 45.74, center_lng: 15.91 },
];

const _LEGACY_MOCK: Listing[] = [
  {
    id: "mock-1",
    external_id: "NJ-10001",
    source: "njuskalo",
    url: "https://www.njuskalo.hr/nekretnine/10001",
    title: "Svijetli stan u centru, 2 sobe",
    deal_type: "rent",
    price: 650,
    currency: "EUR",
    area_m2: 58,
    price_per_m2: 11.21,
    rooms: 2,
    floor: 3,
    total_floors: 6,
    year_built: 1960,
    furnished: true,
    neighborhood: "Donji Grad",
    address: "Ilica 45, Zagreb",
    city: "Zagreb",
    latitude: 45.8131,
    longitude: 15.972,
    nearest_kindergarten_m: 250,
    nearest_school_m: 400,
    nearest_hospital_m: 800,
    nearest_transit_m: 100,
    nearest_park_m: 400,
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop"],
    description: "Potpuno namješten stan na odličnoj lokaciji. Blizu tramvajske stanice. Renoviran 2022, novi kuhinjski elementi.",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "mock-2",
    external_id: "NJ-10002",
    source: "njuskalo",
    url: "https://www.njuskalo.hr/nekretnine/10002",
    title: "Garsonijera na Trešnjevci",
    deal_type: "rent",
    price: 380,
    currency: "EUR",
    area_m2: 32,
    price_per_m2: 11.88,
    rooms: 1,
    floor: 1,
    total_floors: 4,
    year_built: 1975,
    furnished: true,
    neighborhood: "Trešnjevka Sjever",
    address: "Ozaljska 12, Zagreb",
    city: "Zagreb",
    latitude: 45.804,
    longitude: 15.956,
    nearest_kindergarten_m: 400,
    nearest_school_m: 600,
    nearest_hospital_m: 1200,
    nearest_transit_m: 150,
    nearest_park_m: 300,
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop"],
    description: "Mala ali funkcionalna garsonijera. Internet uključen. Idealna za studente ili mlade profesionalce.",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "mock-3",
    external_id: "NJ-10003",
    source: "njuskalo",
    url: "https://www.njuskalo.hr/nekretnine/10003",
    title: "Prostrani 3-sobni stan, Maksimir",
    deal_type: "rent",
    price: 900,
    currency: "EUR",
    area_m2: 85,
    price_per_m2: 10.59,
    rooms: 3,
    floor: 2,
    total_floors: 5,
    year_built: 2005,
    furnished: false,
    neighborhood: "Maksimir",
    address: "Bukovačka 78, Zagreb",
    city: "Zagreb",
    latitude: 45.824,
    longitude: 16.015,
    nearest_kindergarten_m: 300,
    nearest_school_m: 350,
    nearest_hospital_m: 1500,
    nearest_transit_m: 200,
    nearest_park_m: 50,
    images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop"],
    description: "Veliki stan blizu parka Maksimir. Renoviran 2023. Dva balkona, parking mjesto u garaži.",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "mock-4",
    external_id: "IX-20001",
    source: "index-hr",
    url: "https://www.index.hr/oglasi/20001",
    title: "Novogradnja Novi Zagreb, 2 sobe",
    deal_type: "sale",
    price: 185000,
    currency: "EUR",
    area_m2: 62,
    price_per_m2: 2983.87,
    rooms: 2,
    floor: 5,
    total_floors: 8,
    year_built: 2024,
    furnished: false,
    neighborhood: "Novi Zagreb Istok",
    address: "Avenija Dubrovnik 15, Zagreb",
    city: "Zagreb",
    latitude: 45.776,
    longitude: 15.994,
    nearest_kindergarten_m: 200,
    nearest_school_m: 300,
    nearest_hospital_m: 600,
    nearest_transit_m: 100,
    nearest_park_m: 500,
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&h=400&fit=crop"],
    description: "Novogradnja s garažnim mjestom. Useljivo odmah. Energetski razred A+.",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "mock-5",
    external_id: "IX-20002",
    source: "index-hr",
    url: "https://www.index.hr/oglasi/20002",
    title: "Kuća s vrtom, Sesvete",
    deal_type: "sale",
    price: 320000,
    currency: "EUR",
    area_m2: 180,
    price_per_m2: 1777.78,
    rooms: 5,
    floor: null,
    total_floors: 2,
    year_built: 2010,
    furnished: false,
    neighborhood: "Sesvete",
    address: "Jelkovečka 33, Zagreb",
    city: "Zagreb",
    latitude: 45.831,
    longitude: 16.108,
    nearest_kindergarten_m: 500,
    nearest_school_m: 600,
    nearest_hospital_m: 2000,
    nearest_transit_m: 400,
    nearest_park_m: 100,
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&h=400&fit=crop"],
    description: "Obiteljska kuća s velikim vrtom. Mirna lokacija. Garaža za dva automobila.",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "mock-6",
    external_id: "C21-30001",
    source: "century21",
    url: "https://www.century21.hr/30001",
    title: "Penthouse Trnje, pogled na Savu",
    deal_type: "sale",
    price: 450000,
    currency: "EUR",
    area_m2: 120,
    price_per_m2: 3750,
    rooms: 4,
    floor: 8,
    total_floors: 8,
    year_built: 2020,
    furnished: true,
    neighborhood: "Trnje",
    address: "Savska cesta 100, Zagreb",
    city: "Zagreb",
    latitude: 45.799,
    longitude: 15.987,
    nearest_kindergarten_m: 350,
    nearest_school_m: 500,
    nearest_hospital_m: 500,
    nearest_transit_m: 80,
    nearest_park_m: 200,
    images: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&h=400&fit=crop"],
    description: "Luksuzan penthouse s terasom i pogledom na Savu. Smart home sustav. Jacuzzi na terasi.",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "mock-7",
    external_id: "C21-30002",
    source: "century21",
    url: "https://www.century21.hr/30002",
    title: "Studio apartman, Gornji Grad",
    deal_type: "rent",
    price: 550,
    currency: "EUR",
    area_m2: 40,
    price_per_m2: 13.75,
    rooms: 1,
    floor: 2,
    total_floors: 3,
    year_built: 1890,
    furnished: true,
    neighborhood: "Gornji Grad",
    address: "Tkalčićeva 22, Zagreb",
    city: "Zagreb",
    latitude: 45.8155,
    longitude: 15.977,
    nearest_kindergarten_m: 500,
    nearest_school_m: 700,
    nearest_hospital_m: 700,
    nearest_transit_m: 150,
    nearest_park_m: 300,
    images: ["https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=600&h=400&fit=crop"],
    description: "Šarmantan studio u srcu Gornjeg grada. Obnovljena stolarija, parket. Pogled na krovove.",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "mock-8",
    external_id: "RM-40001",
    source: "remax",
    url: "https://www.remax.hr/40001",
    title: "Obiteljski stan, Medveščak",
    deal_type: "rent",
    price: 1100,
    currency: "EUR",
    area_m2: 95,
    price_per_m2: 11.58,
    rooms: 3,
    floor: 4,
    total_floors: 6,
    year_built: 1985,
    furnished: false,
    neighborhood: "Medveščak",
    address: "Medveščak 44, Zagreb",
    city: "Zagreb",
    latitude: 45.827,
    longitude: 15.981,
    nearest_kindergarten_m: 150,
    nearest_school_m: 200,
    nearest_hospital_m: 400,
    nearest_transit_m: 200,
    nearest_park_m: 250,
    images: ["https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=600&h=400&fit=crop"],
    description: "Prostran stan u mirnom dijelu Medveščaka. Podrumska ostava. Lift u zgradi.",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "mock-9",
    external_id: "CZ-50001",
    source: "crozilla",
    url: "https://www.crozilla.com/50001",
    title: "Dvosobni stan, Črnomerec",
    deal_type: "sale",
    price: 165000,
    currency: "EUR",
    area_m2: 55,
    price_per_m2: 3000,
    rooms: 2,
    floor: 1,
    total_floors: 4,
    year_built: 1970,
    furnished: false,
    neighborhood: "Črnomerec",
    address: "Ilica 300, Zagreb",
    city: "Zagreb",
    latitude: 45.8175,
    longitude: 15.939,
    nearest_kindergarten_m: 300,
    nearest_school_m: 450,
    nearest_hospital_m: 1000,
    nearest_transit_m: 100,
    nearest_park_m: 400,
    images: ["https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=600&h=400&fit=crop"],
    description: "Renoviran stan na mirnoj lokaciji blizu centra. Novi prozori i fasada.",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "mock-10",
    external_id: "CZ-50002",
    source: "crozilla",
    url: "https://www.crozilla.com/50002",
    title: "Stan s balkonom, Peščenica",
    deal_type: "rent",
    price: 700,
    currency: "EUR",
    area_m2: 65,
    price_per_m2: 10.77,
    rooms: 2,
    floor: 3,
    total_floors: 5,
    year_built: 1990,
    furnished: true,
    neighborhood: "Peščenica",
    address: "Slavonska avenija 55, Zagreb",
    city: "Zagreb",
    latitude: 45.8105,
    longitude: 16.009,
    nearest_kindergarten_m: 200,
    nearest_school_m: 350,
    nearest_hospital_m: 800,
    nearest_transit_m: 50,
    nearest_park_m: 350,
    images: ["https://images.unsplash.com/photo-1600210492493-0946911123ea?w=600&h=400&fit=crop"],
    description: "Svijetli stan s velikim balkonom. Parking uključen. Klimatizacija u svim sobama.",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "mock-11",
    external_id: "NJ-10004",
    source: "njuskalo",
    url: "https://www.njuskalo.hr/nekretnine/10004",
    title: "Adaptiran stan, Dubrava",
    deal_type: "sale",
    price: 120000,
    currency: "EUR",
    area_m2: 48,
    price_per_m2: 2500,
    rooms: 2,
    floor: 2,
    total_floors: 4,
    year_built: 1980,
    furnished: false,
    neighborhood: "Gornja Dubrava",
    address: "Dubrava 150, Zagreb",
    city: "Zagreb",
    latitude: 45.834,
    longitude: 16.058,
    nearest_kindergarten_m: 200,
    nearest_school_m: 300,
    nearest_hospital_m: 1800,
    nearest_transit_m: 300,
    nearest_park_m: 500,
    images: ["https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=600&h=400&fit=crop"],
    description: "Potpuno adaptiran 2019. Odlična cijena za kvadraturu. Mirna ulica.",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true,
  },
  {
    id: "mock-12",
    external_id: "IX-20003",
    source: "index-hr",
    url: "https://www.index.hr/oglasi/20003",
    title: "Garsonijera, Studentski Grad",
    deal_type: "rent",
    price: 350,
    currency: "EUR",
    area_m2: 28,
    price_per_m2: 12.5,
    rooms: 1,
    floor: 6,
    total_floors: 10,
    year_built: 1975,
    furnished: true,
    neighborhood: "Maksimir",
    address: "Studentski grad bb, Zagreb",
    city: "Zagreb",
    latitude: 45.82,
    longitude: 16.01,
    nearest_kindergarten_m: 600,
    nearest_school_m: 800,
    nearest_hospital_m: 1500,
    nearest_transit_m: 100,
    nearest_park_m: 150,
    images: ["https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=600&h=400&fit=crop"],
    description: "Idealno za studente. Blizu FER-a i PMF-a. Tramvajska stanica ispred zgrade.",
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true,
  },
] as Listing[];

export const MOCK_LISTINGS: Listing[] = SCRAPED_LISTINGS.length > 0
  ? SCRAPED_LISTINGS
  : _LEGACY_MOCK;
